'use strict'

export const A_GET_TODO_LIST = 'A_GET_TODO_LIST'
export const M_GET_TODO_LIST = 'M_GET_TODO_LIST'

export const M_CREATE_TODO_LIST_GROUP = 'M_CREATE_TODO_LIST_GROUP'

export const M_ADD_TODO_LIST_ITEM = 'M_ADD_TODO_LIST_ITEM'

export const A_CREATE_TASK_GROUP = 'A_CREATE_TASK_GROUP'
export const M_CREATE_TASK_GROUP = 'M_CREATE_TASK_GROUP'

export const A_GET_TASK_GROUP = 'A_GET_TASK_GROUP'
export const M_GET_TASK_GROUP = 'M_GET_TASK_GROUP'

export const A_CREATED_TASK = 'A_CREATED_TASK'
